services:
  web:
    build: .
    container_name: cinema_web
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=devops-final-secret
      - DATABASE_URL=sqlite:////app/data/app.db
    volumes:
      - db_data:/app/data
    restart: unless-stopped

volumes:
  db_data:
